export const Skill_data = [
  {
    skill_name: "HTML5",
    Image: "/html.png",
    width: 80,
    height: 80,
    alt: "Logo HTML5",
  },
  {
    skill_name: "CSS",
    Image: "/css.png",
    width: 80,
    height: 80,
    alt: "Logo CSS3",
  },
  {
    skill_name: "JavaScript",
    Image: "/js.png",
    width: 65,
    height: 65,
    alt: "Logo JavaScript",
  },
  {
    skill_name: "Tailwind CSS",
    Image: "/tailwind.png",
    width: 80,
    height: 80,
    alt: "Logo Tailwind CSS",
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    height: 80,
    alt: "Logo React",
  },
  {
    skill_name: "Redux",
    Image: "/redux.png",
    width: 80,
    height: 80,
    alt: "Logo Redux",
  },
  {
    skill_name: "TypeScript",
    Image: "/ts.png",
    width: 80,
    height: 80,
    alt: "Logo TypeScript",
  },
  {
    skill_name: "Next.js 13",
    Image: "/next.png",
    width: 80,
    height: 80,
    alt: "Logo Next.js 13",
  },
  {
    skill_name: "Framer Motion",
    Image: "/framer.png",
    width: 80,
    height: 80,
    alt: "Logo Framer Motion",
  },
  {
    skill_name: "Node.js",
    Image: "/node-js.png",
    width: 80,
    height: 80,
    alt: "Logo Node.js",
  },
  {
    skill_name: "MongoDB",
    Image: "/mongodb.png",
    width: 40,
    height: 40,
    alt: "Logo MongoDB",
  },
  {
    skill_name: "Sass",
    Image: "/sass.svg",
    width: 80,
    height: 80,
    alt: "Logo Sass",
  }
];
